In [2]:
pip install bitermplus

C:\Users\xiu03\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [3]:
pip install pyLDAvis

C:\Users\xiu03\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


Note: you may need to restart the kernel to use updated packages.


In [4]:
pip install tmplot

C:\Users\xiu03\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


Note: you may need to restart the kernel to use updated packages.


In [5]:
import bitermplus as btm
import numpy as np
import pandas as pd
import csv
from tqdm import tqdm
import logging
from gensim import corpora
from gensim.models import TfidfModel, LdaMulticore
from gensim.models.coherencemodel import CoherenceModel
import matplotlib.pyplot as plt
import pyLDAvis
import pyLDAvis.gensim_models as gensimvis
import tmplot as tmp


# Importing datatexts = []
#with open('sentence_token_Ba Na Hills.csv', 'r', encoding='utf-8') as f:
#    for line in f:
#        line = line.replace('\n', '')
#        texts.append(line.replace('@', ' '))
#print(texts)       
file = open('sentence_token_Ba Na Hills.csv', 'r', encoding='utf-8')
texts = [' '.join(row) for row in csv.reader(file)]

C:\Users\xiu03\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [6]:
#btm model#
X,vocabulary, vocab_dict = btm.get_words_freqs(texts)

C:\Users\xiu03\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [7]:
vocabulary

C:\Users\xiu03\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


array(['16th', '19th', '20180440cable', ..., 'zipline', 'zombies', 'zoo'],
      dtype='<U22')

In [8]:
vocab_dict

C:\Users\xiu03\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


{'poor': 2520,
 'mans': 1988,
 'amusement': 102,
 'park': 2379,
 'copying': 720,
 'western': 3751,
 'motifs': 2126,
 'much': 2144,
 'enjoy': 1085,
 'granted': 1431,
 'rained': 2662,
 'tacky': 3323,
 'feel': 1243,
 'areas': 153,
 'modeled': 2100,
 'regions': 2734,
 'eg': 1046,
 'cliche': 585,
 'german': 1382,
 'town': 3467,
 'golden': 1413,
 'bridge': 382,
 'feature': 1238,
 'attraction': 204,
 'feels': 1245,
 'authentic': 212,
 'packed': 2355,
 'tourists': 3459,
 'get': 1384,
 'know': 1801,
 'cable': 433,
 'car': 460,
 'going': 1411,
 'least': 1842,
 'twenty': 3537,
 'minutes': 2075,
 'stay': 3188,
 'away': 226,
 'covid19': 754,
 'may': 2016,
 'reopened': 2764,
 'charging': 532,
 'full': 1347,
 'price': 2571,
 'admission': 46,
 'tickets': 3409,
 'shops': 2999,
 'restaurants': 2799,
 'attractions': 205,
 'remain': 2749,
 'shuttered': 3024,
 'gondolas': 1416,
 'run': 2870,
 'find': 1262,
 'trapped': 3485,
 'hour': 1596,
 'service': 2969,
 'resumes': 2805,
 'keep': 1774,
 'mind': 2067,
 '

In [9]:
docs_vec = btm.get_vectorized_docs(texts,vocabulary)
docs_vec

C:\Users\xiu03\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


[array([2144, 1085]),
 array([2662]),
 array([3323, 1243,  153, 2100, 2734, 1046]),
 array([ 585, 3467]),
 array([1238,  204, 1245,  212, 2355, 3459]),
 array([1801,  433,  460, 1411, 1842, 3537, 2075]),
 array([], dtype=int32),
 array([2379, 2764,  532, 1347, 2571,   46, 3409, 2999, 2799,  205, 2749,
        3024]),
 array([1416, 2870, 1262, 3485, 1596, 2969, 2805]),
 array([2067, 3663]),
 array([ 223,  786, 2426, 3415, 3661]),
 array([2539, 3661, 2379, 2765]),
 array([ 355, 2510, 2479, 3383, 2716, 2479, 3649, 1264,  831, 2893,  310,
        3713, 2107, 3510]),
 array([ 983, 2813, 2480,  261, 3730]),
 array([2813,  261, 2259]),
 array([2479, 2259, 2227]),
 array([3509, 1206]),
 array([2508,  382, 1410]),
 array([3713,  831, 3713, 2107]),
 array([ 446, 2940, 2479]),
 array([ 446, 2940, 3323, 1173, 3457, 3484, 2022, 1408]),
 array([], dtype=int32),
 array([3661]),
 array([ 161,  174, 3618, 2038, 3159, 2999, 2799,  205, 2281, 1105, 1242,
        1537, 2546]),
 array([1092, 2281, 2220]),


In [10]:
biterms = btm.get_biterms(docs_vec)
biterms

C:\Users\xiu03\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


[[[1085, 2144]],
 [[1243, 3323],
  [153, 3323],
  [2100, 3323],
  [2734, 3323],
  [1046, 3323],
  [153, 1243],
  [1243, 2100],
  [1243, 2734],
  [1046, 1243],
  [153, 2100],
  [153, 2734],
  [153, 1046],
  [2100, 2734],
  [1046, 2100],
  [1046, 2734]],
 [[585, 3467]],
 [[204, 1238],
  [1238, 1245],
  [212, 1238],
  [1238, 2355],
  [1238, 3459],
  [204, 1245],
  [204, 212],
  [204, 2355],
  [204, 3459],
  [212, 1245],
  [1245, 2355],
  [1245, 3459],
  [212, 2355],
  [212, 3459],
  [2355, 3459]],
 [[433, 1801],
  [460, 1801],
  [1411, 1801],
  [1801, 1842],
  [1801, 3537],
  [1801, 2075],
  [433, 460],
  [433, 1411],
  [433, 1842],
  [433, 3537],
  [433, 2075],
  [460, 1411],
  [460, 1842],
  [460, 3537],
  [460, 2075],
  [1411, 1842],
  [1411, 3537],
  [1411, 2075],
  [1842, 3537],
  [1842, 2075],
  [2075, 3537]],
 [[2379, 2764],
  [532, 2379],
  [1347, 2379],
  [2379, 2571],
  [46, 2379],
  [2379, 3409],
  [2379, 2999],
  [2379, 2799],
  [205, 2379],
  [2379, 2749],
  [2379, 3024],
  [

In [11]:
#btm model#
X,vocabulary, vocab_dict = btm.get_words_freqs(texts)
docs_vec = btm.get_vectorized_docs(texts,vocabulary)
biterms = btm.get_biterms(docs_vec)
model = btm.BTM(X,vocabulary,seed=12321,T=8,M=2,alpha=50/8,beta=0.01) #T => Topic 수
model.fit(biterms,iterations=200)
p_zd = model.transform(docs_vec)
perplexity = btm.perplexity(model.matrix_topics_words_,p_zd,X,8)
coherence = btm.coherence(model.matrix_topics_words_,X,M=20)
perplexity = model.perplexity_
coherence = model.coherence_
#btm model#

print(perplexity)
print(coherence)

C:\Users\xiu03\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
100%|███████████████████████████████████████████████████████████████████████████| 3022/3022 [00:00<00:00, 33213.46it/s]


714.6294619111794
[-1.68894998 -2.25533221 -2.28504078 -2.15598162 -2.55389952 -0.17589067
 -2.60050866 -4.36309862]


In [12]:
tmp.report(model=model,docs=texts)


C:\Users\xiu03\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
C:\Users\xiu03\anaconda3\lib\site-packages\sklearn\manifold\_t_sne.py:691: FutureWarning: 'square_distances' has been introduced in 0.24 to help phase out legacy squaring behavior. The 'legacy' setting will be removed in 1.1 (renaming of 0.26), and the default setting will be changed to True. In 1.3, 'square_distances' will be removed altogether, and distances will be squared by default. Set 'square_distances'=True to silence this warning.
  warnings.warn(
